---
db_mountPoint: /home/seandersont/gitea_db
db_nfsShare: truenas.seandersontech.com:/mnt/tank/nfsshare/gitea_db
gitea_mountPoint: /home/seandersont/gitea
gitea_nfsShare: truenas.seandersontech.com:/mnt/tank/nfsshare/gitea
