---
- name: Update hosts to latest version
  hosts: deathstar_servers 
  become: true
<<<<<<< HEAD
=======

>>>>>>> parent of c85acca (changed become to yes instead of true)
  tasks:
    - name: Update host applications to latest version
      yum: 
        name: '*'
        state: latest
      register: yum_results

#    - debug:
#        var: yum_results.results

