---
- name: Update hosts to latest version
  hosts: deathstar_servers 
  become: true
  become_user: seandersont

  tasks:
    - name: Update host applications to latest version
      yum: 
        name: '*'
        state: latest
