---
- name: manage libvirt guests
  user: seandersont
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: Stop Fedora Server
      virt:
        name: fedsvr30
        command: shutdown
        state: shutdown 
    - name: get VM XML
      virt:
        name: fedsvr30
        command: get_xml
      register: out
    - name: test create
      virt:
        name: fedsvr30
        command: create
      register: createTest
    - name: List VM's
      virt:
        name: fedsvr30
        command: list_vms

    - debug: var=out
    - debug: var=createTest
