---
- name: Create postgres container
  containers.podman.podman_container:
    name: gitea-pgdb
    user: 1000
    state: quadlet
    network: gitea-net
    image: docker.io/postgres:latest
    tty: true
    shm_size: 128mb
    volume: 
      - /home/seandersont/gitea_db:/var/lib/postgresql/data
    env:
      POSTGRES_USER: "gitea"
      POSTGRES_PASSWORD: "MicrophoneExtensionBalb0a"
      POSTGRES_DB: "gitea"
    quadlet_options:
      - "AutoUpdate=registry"
      - |
        [Install]
        WantedBy=default.target


- name: start gitea-app systemd unit
  ansible.builtin.systemd:
    name: gitea-pgdb
    daemon_reload: true
    state: started
    enabled: true

