---
- name: Create postgres container
  containers.podman.podman_container:
    name: gitea-pgdb
    user: 1000
    state: started
    network: gitea-net
    image: docker.io/postgres:latest
    restart_policy: "always"
    tty: true
    shm_size: 128mb
    volume: 
      - /home/seandersont/gitea_db:/var/lib/postgresql/data
    env:
      POSTGRES_USER: "gitea"
      POSTGRES_PASSWORD: "MicrophoneExtensionBalb0a"
      POSTGRES_DB: "gitea"

