---
- name: Set MOTD on webservers
  hosts: goldsquad
  vars:
  become: true
  tasks:
    - name: Get MOTD with echo
      ansible.builtin.command: cat /etc/motd
      register: motd

    - ansible.builtin.debug:
        var: motd

    - name: Set MOTD
      ansible.builtin.template:
        src: template/motd
        dest: /etc/motd
...