---
- name: Set MOTD on webservers
  hosts: goldsquad
  vars:
  become: true
  tasks:
    - name: Get MOTD with echo
      ansible.builtin.command: cat /etc/motd
      register: motd

    - debug:
      msg: {{motd}}

    - name: Set MOTD
      template:
        src: template/motd
        dest: /etc/motd
...